name: combo_maker
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-428.0.dev <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  excel: ^3.0.0
  cupertino_icons: ^1.0.2
  math_expressions: ^2.4.0
  firebase_core: ^2.23.0
  cloud_firestore: ^4.13.0
  path_provider: ^2.1.1
  carousel_slider: ^4.2.1
  flutter_riverpod: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true